# project_root/.travis.yml
matrix:
include:
- language: node_js # Your language e.g. node_js, python
node_js:
- '10' # node_js version
dist: trusty
addons:
  sonarcloud:
    organization: "swsnu"
    token:
      secure: "nVlGWugKnSmqIwTjXhUdxqz+iLSV7KDSWcPfZUtoZ+s+T3zrAk4oMgwGGT2FcdkTorNBLKcF0rho772IC2qj28Cjy1x1DGIVi1FIFQF36Qljc7H19/qeVKnuzwJXYSfisOUAEnoJCyBx3e5Z3T1SKnRmh4gCIigAtZ5mGh4B6D6RqmHXrmbLJS9CttFpDUFX2NEFJjbofECD2W21PP15v71YPXAPdiO3FEkR2BbIzvqbJoMzFCcLJEJqlgnEB2k2Kb0GzyJ8QmWN7eo0Y2MwSeN/xfuJryDTZyCmFA294zEwKP/jhdd7wX9zsTYga3ADuOvJqvS29Cqe2ezETiOLZ8B68wPNdinsmcA/NJoo6EFpZABZuImEUS3O7epGio1kU1tpjkBXEjpyXWt++B4e+39FonMmbBTfGt3M6BXwZCl8lZlEH3STbn4QKVsMCxRyjJwJBF87xSAQVcEv1uXcFLsHgtvuOAVALH/zx6kI0QO0yyXixFdLQ9sRhR4VPyDRkNwofG8Sqted8P2fX+wvSFQjImesVMwQhYscAX0pfB/Iho6xhKS3yZQQcuuq6ywvvbxTQUTuGqMGGA4pVX9/sMVBuiGD5hH1F7sYwdhdI9NMp6Gayal3TCBVmEbv7gzYN9QK7ZeOD9VH2gVWtctQGEzNasDW5wTeekdyUaEoaII=" 
before_install: # Script to run before install
- cd frontend
install: # Script to install required packages
- yarn install
script: # Script to test your build
- ./node_modules/.bin/eslint src
- yarn test --coverage --watchAll=false
- sonar-scanner
# - language: python
# python: 3.6
