# project_root/.travis.yml
matrix: 
  include: 
  - language: node_js
    node_js: 
    - '10'
    dist: trusty
    addons: 
      sonarcloud: 
        organization: "swsnu"
        token: 
          secure: "nVlGWugKnSmqIwTjXhUdxqz+iLSV7KDSWcPfZUtoZ+s+T3zrAk4oMgwGGT2FcdkTorNBLKcF0rho772IC2qj28Cjy1x1DGIVi1FIFQF36Qljc7H19/qeVKnuzwJXYSfisOUAEnoJCyBx3e5Z3T1SKnRmh4gCIigAtZ5mGh4B6D6RqmHXrmbLJS9CttFpDUFX2NEFJjbofECD2W21PP15v71YPXAPdiO3FEkR2BbIzvqbJoMzFCcLJEJqlgnEB2k2Kb0GzyJ8QmWN7eo0Y2MwSeN/xfuJryDTZyCmFA294zEwKP/jhdd7wX9zsTYga3ADuOvJqvS29Cqe2ezETiOLZ8B68wPNdinsmcA/NJoo6EFpZABZuImEUS3O7epGio1kU1tpjkBXEjpyXWt++B4e+39FonMmbBTfGt3M6BXwZCl8lZlEH3STbn4QKVsMCxRyjJwJBF87xSAQVcEv1uXcFLsHgtvuOAVALH/zx6kI0QO0yyXixFdLQ9sRhR4VPyDRkNwofG8Sqted8P2fX+wvSFQjImesVMwQhYscAX0pfB/Iho6xhKS3yZQQcuuq6ywvvbxTQUTuGqMGGA4pVX9/sMVBuiGD5hH1F7sYwdhdI9NMp6Gayal3TCBVmEbv7gzYN9QK7ZeOD9VH2gVWtctQGEzNasDW5wTeekdyUaEoaII=" 
    before_install:
    - cd frontend
    install: # Script to install required packages
    - npm install
    - npm install coveralls
    script: # Script to test your build
    - npm test -- --coverage --watchAll=false
    - sonar-scanner
    after_success: 
    - cat ./coverage/lcov/info | ./node_modules/coveralls/bin/coveralls.js
    
  - language: python
    dist: xenial
    services:
    - mysql
    python: 
    - "3.7"
    - "3.8"
    before_install: 
    - mysql -e "CREATE DATABASE tutoringmachine_db;"
    - mysql -e "CREATE USER 'tutoring'@'localhost' IDENTIFIED BY 'machine';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* to 'tutoring'@'localhost';"
    - cd backend
    install: 
    - pip install -r requirement_tutoring.txt
    - pip install coveralls
    script: 
    - python manage.py makemigrations tutoring
    - python manage.py migrate
    - pylint manage.py --exit-zero
    - coverage run --source='./tutoring' manage.py test
    - coverage report -m
    after_success: 
    - coveralls
