# project_root/.travis.yml
matrix:
include:
- language: node_js # Your language e.g. node_js, python
node_js:
- '10' # node_js version
before_install: # Script to run before install
- cd TutoringMachine/frontend
install: # Script to install required packages
- npm install
script: # Script to test your build
- ./node_modules/.bin/eslint src
- npm test -- --coverage --watchAll=false
# - language: python
# python: 3.6
