# Generated by Django 2.2.6 on 2019-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='detailed_address_x',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='tutee',
            name='detailed_address_y',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
