# Generated by Django 2.2.6 on 2019-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20191101_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='detailed_address_x',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='tutor',
            name='detailed_address_y',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
