# Generated by Django 2.2.6 on 2019-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20191105_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(null=True, upload_to='tutor/'),
        ),
    ]
