# Generated by Django 2.2.6 on 2019-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_auto_20191105_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
