# Generated by Django 2.2.6 on 2019-12-02 06:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20191106_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('math', 'Math'), ('korean', 'Korean'), ('english', 'English'), ('society', 'Society'), ('science', 'Science')], max_length=5),
        ),
    ]
