# Generated by Django 2.2.6 on 2019-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_auto_20191202_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
